### ISSUE TITLE
I can get access to the API

### ISSUE THREAD

**Issue by carlos-ssh** [shevabam/breaking-bad-quotes#16]
I have this issue: 
![Screen Shot 2022-01-30 at 10 02 30](https://user-images.githubusercontent.com/22258274/151707268-2f49ce3f-09bc-4075-a880-9f426c4a9bd5.png)

**Comment by shevabam** [comment]
This must be because the quota has been reached.
It will be good on February 1st.
I will change the hosting to avoid this kind of error.
