### ISSUE TITLE
CORS error when there wasn't one before?

### ISSUE THREAD

**Issue by d-herz** [shevabam/breaking-bad-quotes#17]
Hello and thank you for this fun API. i recently used your API in a project for a class I am taking. It was working fine this whole time until today I am now getting a "CORS" rejection. Is there a quota or something I did wrong? Thanks in advance!

**Comment by shevabam** [comment]
Hello,
This must be because the quota has been reached.
It will be good on May 1st.
I plan to change host soon to avoid this kind of error.

**Comment by d-herz** [comment]
Ok good to know, thanks again!
