### ISSUE TITLE
Heroku app down

### ISSUE THREAD

**Issue by ssaunier** [shevabam/breaking-bad-quotes#18]
Hello @shevabam 👋 ,

Thank for hosting this project! It seems that the main app went down, did you try to `heroku restart` it?

<img width="937" alt="Screenshot 2022-04-28 at 12 41 03" src="https://user-images.githubusercontent.com/414418/165735405-e1203aa7-c087-4391-b257-105c606daf27.png">

Thank you!

**Comment by shevabam** [comment]
Hello!
The app is down because the quota has been reached. I'm using the free plan of Heroku.
It will be good on May 1st.
I plan to change host soon to avoid this kind of error.
Sorry for the inconvenience

**Comment by ssaunier** [comment]
Thank you for the update!
